<a href="https://colab.research.google.com/github/renatamontanhana/Machine_Learning_Algoritmo_Naive_Bayes_CDPRO/blob/main/M4A18_NumPy_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTK4gQ9nhwHHaSXMHpeggWg7twwMCgb877smkRmtkmDeDoGF9Z6&usqp=CAU)

# <font color='BLUE'>Cientista de Dados na Prática </font>

# <font color='GREEN'>Módulo 4 - Análise Exploratória dos Dados</font>

### <font color='GREY'> Numpy - Manipulando arquivos Multidimensionais </font>



# Numpy - Análise de Dados  


<p> Simbóra aprender a trabalhar coma biblioteca Numpy.


In [23]:
# Importando a biblioteca numpy
import numpy as np

In [24]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [25]:
type(one_dim)

numpy.ndarray

In [26]:
# Imprimindo um array.
one_dim.ndim

1

In [27]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [28]:
# Imprimindo o array
two_dim.ndim

2

In [29]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.24056874, 0.79099656],
       [0.46841406, 0.90218743],
       [0.18326479, 0.49881023],
       [0.21231   , 0.85947247],
       [0.06440407, 0.17400919]])

In [30]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [31]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Arrays x Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [33]:
# Criando uma lista em Python.
lista = [1,2,3]

In [34]:
lista

[1, 2, 3]

In [35]:
type(lista)

list

In [36]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [37]:
type(lista)

list

In [38]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [39]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [40]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [41]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [42]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [43]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [44]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [45]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [ ]:
a * 2

# Métodos e Atributos Úteis

In [50]:
# Métodos disponíveis (digite o . pressione tab).
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [52]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [54]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [55]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [56]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [57]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [58]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [59]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
two_dim.dtype

dtype('int64')

In [61]:
two_dim.size

6

In [62]:
# mostra o compromento em bytes
two_dim.itemsize

8

In [63]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [64]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [65]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [69]:
tree = np.random.random((5,3))

In [101]:
tree.shape

(5, 3)

In [71]:
tree

array([[0.72565626, 0.73338696, 0.33462277],
       [0.81222767, 0.94675469, 0.96186367],
       [0.26755625, 0.31789838, 0.51495348],
       [0.97509977, 0.35560601, 0.57319132],
       [0.10047701, 0.4347515 , 0.11057464]])

In [72]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.72565626, 0.73338696, 0.33462277, 0.81222767, 0.94675469],
       [0.96186367, 0.26755625, 0.31789838, 0.51495348, 0.97509977],
       [0.35560601, 0.57319132, 0.10047701, 0.4347515 , 0.11057464]])

In [73]:
tree.reshape(-1)

array([0.72565626, 0.73338696, 0.33462277, 0.81222767, 0.94675469,
       0.96186367, 0.26755625, 0.31789838, 0.51495348, 0.97509977,
       0.35560601, 0.57319132, 0.10047701, 0.4347515 , 0.11057464])

In [74]:
t=tree.reshape(1,15)
t

array([[0.72565626, 0.73338696, 0.33462277, 0.81222767, 0.94675469,
        0.96186367, 0.26755625, 0.31789838, 0.51495348, 0.97509977,
        0.35560601, 0.57319132, 0.10047701, 0.4347515 , 0.11057464]])

In [75]:
t

array([[0.72565626, 0.73338696, 0.33462277, 0.81222767, 0.94675469,
        0.96186367, 0.26755625, 0.31789838, 0.51495348, 0.97509977,
        0.35560601, 0.57319132, 0.10047701, 0.4347515 , 0.11057464]])

In [76]:
t.shape

(1, 15)

In [77]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [108]:
# Transforma em um array de uma linha.
two_dim

array([10, 10, 10,  1,  2,  3,  4,  5,  6])

In [115]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [116]:
two_dim

array([2, 3, 4, 5, 6])

In [117]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

# Acessando Dimensões no Array

In [83]:
# Importando o Numpy
import numpy as np

In [84]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [119]:
my_array

array([[0.47527907, 0.85026737],
       [0.95717076, 0.45722405],
       [0.6483454 , 0.34599355],
       [0.60839308, 0.58638103],
       [0.48870785, 0.78763925],
       [0.53608542, 0.8544098 ],
       [0.49280709, 0.68839022],
       [0.71360588, 0.70194807],
       [0.71185629, 0.53565326],
       [0.35153879, 0.03774444]])

In [118]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.47527907, 0.85026737])

In [120]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.47527907413574977

In [121]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.8502673746861988

In [122]:
# Segundo elemento da coluna 1
my_array[1][1]

0.45722405049179504

In [123]:
my_array

array([[0.47527907, 0.85026737],
       [0.95717076, 0.45722405],
       [0.6483454 , 0.34599355],
       [0.60839308, 0.58638103],
       [0.48870785, 0.78763925],
       [0.53608542, 0.8544098 ],
       [0.49280709, 0.68839022],
       [0.71360588, 0.70194807],
       [0.71185629, 0.53565326],
       [0.35153879, 0.03774444]])

In [91]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.85026737, 0.45722405, 0.34599355])

In [92]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([8.50267375, 4.5722405 , 3.45993547, 5.86381033, 7.8763925 ,
       8.54409797, 6.88390219, 7.0194807 , 5.35653257, 0.37744443])

In [93]:
# Comparação retorna indices
my_array > 0.50

array([[False,  True],
       [ True, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [94]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.85026737, 0.95717076, 0.6483454 , 0.60839308, 0.58638103,
       0.78763925, 0.53608542, 0.8544098 , 0.68839022, 0.71360588,
       0.70194807, 0.71185629, 0.53565326])

# Trabalhando com Valores Missing

* **Missing Values** são valores faltantes em colunas, esses podem ser oriundos de falhas em cargas de dados, falhas em crawlers ou até mesmo corrupção de dados.

* Missing Values podem ser um problema em várias situações, como por exemplo, algoritmos de machine learning que não trabalham bem com dados faltantes.

* Estes também podem atrapalhar resultados de análises.

* Vamos aprender como encontrar missing values na base de dados e como manipular esses valores.

In [100]:
import matplotlib


import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

FileNotFoundError: ignored

In [99]:
dataset.head()

NameError: ignored

In [ ]:
# Consultando linhas com valores faltantes.
dataset.isnull().sum()

In [ ]:
#Com este comando removemos todas as linhas onde tenha pela menos um registro faltante em algum atributo.
dataset.dropna(inplace=True)

In [ ]:
# É possível ainda, remover somente linhas que estejam com valores faltantes em todas as colunas, veja:
dataset.dropna(how='all', inplace=True)

In [ ]:
#preenche com a media dos valores da coluns floors os values null
dataset['floors'].fillna(dataset['floors'].mean(), inplace=True)

In [ ]:
#preenche com 1 os values null da coluna bedrooms
dataset['bedrooms'].fillna(1, inplace=True)

# Visualização Gráfica - Extraindo Insights

* Vamos agora trabalhar com um tipo de gráfico muito interessante.

* Os gráficos do tipo Boxplot são excelentes ferramentas de análise de dados, principalmente para identificar _**outliers**_.

In [ ]:
import matplotlib

In [ ]:
import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

In [ ]:
# Plota gráfico do tipo Boxplot da coluna bedrooms
# Esse gráfico é muito rico e é possível visualizar Outliers
%matplotlib notebook
matplotlib.style.use('ggplot')

dataset.boxplot(column='bedrooms')

In [ ]:
# Visualizando os estilos de layout disponível
matplotlib.style.available

In [ ]:
# Plota boxplot da coluna 'price' por número de quartos
%matplotlib notebook
dataset.boxplot(column='price', by='bedrooms')

**Correlação **

In [ ]:
# Imprime a correlação de todas as colunas do dataframe (person)
dataset.corr()

In [ ]:
dataset.corr('spearman')

In [ ]:
# Imprime a correlação de spearman (esta leva em consideração a correção positiva e negativa)
dataset.corr('spearman')

In [ ]:
# Imprime a correção de algumas colunas
dataset[['bedrooms','bathrooms','floors','grade','price']].corr()

# Fim

## Valeu!

### #Instagram - Ciencia dos Dados <a href="http://instagram.com/cienciadosdados">instagram.com/cienciadosdados</a>