<a href="https://colab.research.google.com/github/renatamontanhana/Machine_Learning_Algoritmo_Naive_Bayes_CDPRO/blob/main/M4A18_NumPy_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTK4gQ9nhwHHaSXMHpeggWg7twwMCgb877smkRmtkmDeDoGF9Z6&usqp=CAU)

# <font color='BLUE'>Cientista de Dados na Prática </font>

# <font color='GREEN'>Módulo 4 - Análise Exploratória dos Dados</font>

### <font color='GREY'> Numpy - Manipulando arquivos Multidimensionais </font>



# Numpy - Análise de Dados  


<p> Simbóra aprender a trabalhar coma biblioteca Numpy.


In [ ]:
# Importando a biblioteca numpy
import numpy as np

In [ ]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
type(one_dim)

numpy.ndarray

In [ ]:
# Imprimindo um array.
one_dim.ndim

1

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
# Imprimindo o array
two_dim.ndim

2

In [ ]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.92990152, 0.38584198],
       [0.9405896 , 0.73402847],
       [0.72284162, 0.53289995],
       [0.17819585, 0.08291267],
       [0.01128985, 0.49163325]])

In [ ]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Arrays x Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [ ]:
# Criando uma lista em Python.
lista = [1,2,3]

In [ ]:
lista

[1, 2, 3]

In [ ]:
type(lista)

list

In [ ]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
type(lista)

numpy.ndarray

In [ ]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [ ]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [ ]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [ ]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [ ]:
# Faz o calculo usando as listas
pesos / altura ** 2

In [ ]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [ ]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [ ]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [ ]:
a * 2

# Métodos e Atributos Úteis

In [ ]:
# Métodos disponíveis (digite o . pressione tab).
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [ ]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [ ]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [ ]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [ ]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [ ]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_dim.dtype

dtype('int64')

In [ ]:
two_dim.size

6

In [ ]:
# mostra o compromento em bytes
two_dim.itemsize

8

In [ ]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
tree = np.random.random((5,3))

In [ ]:
tree.shape

(5, 3)

In [ ]:
tree

array([[0.45945935, 0.67230064, 0.99821147],
       [0.45936574, 0.45180989, 0.51396428],
       [0.68794228, 0.1241184 , 0.648467  ],
       [0.26473976, 0.86970892, 0.18814052],
       [0.59250261, 0.92620115, 0.30718967]])

In [ ]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.45945935, 0.67230064, 0.99821147, 0.45936574, 0.45180989],
       [0.51396428, 0.68794228, 0.1241184 , 0.648467  , 0.26473976],
       [0.86970892, 0.18814052, 0.59250261, 0.92620115, 0.30718967]])

In [ ]:
tree.reshape(-1)

array([0.45945935, 0.67230064, 0.99821147, 0.45936574, 0.45180989,
       0.51396428, 0.68794228, 0.1241184 , 0.648467  , 0.26473976,
       0.86970892, 0.18814052, 0.59250261, 0.92620115, 0.30718967])

In [ ]:
t=tree.reshape(1,15)
t

array([[0.45945935, 0.67230064, 0.99821147, 0.45936574, 0.45180989,
        0.51396428, 0.68794228, 0.1241184 , 0.648467  , 0.26473976,
        0.86970892, 0.18814052, 0.59250261, 0.92620115, 0.30718967]])

In [ ]:
t

array([[0.45945935, 0.67230064, 0.99821147, 0.45936574, 0.45180989,
        0.51396428, 0.68794228, 0.1241184 , 0.648467  , 0.26473976,
        0.86970892, 0.18814052, 0.59250261, 0.92620115, 0.30718967]])

In [ ]:
t.shape

(1, 15)

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [ ]:
# Transforma em um array de uma linha.
two_dim

array([10, 10,  1,  2,  3,  4,  5,  6])

In [ ]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [ ]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

# Acessando Dimensões no Array

In [ ]:
# Importando o Numpy
import numpy as np

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [ ]:
my_array

In [ ]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

In [ ]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

In [ ]:
# Primeiro elemento da coluna 1
my_array[0][1]

In [ ]:
# Segundo elemento da coluna 1
my_array[1][1]

In [ ]:
my_array

In [ ]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

In [ ]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

In [ ]:
# Comparação retorna indices
my_array > 0.50

In [ ]:
# Acessando valores por índices
my_array[my_array > 0.50]

# Trabalhando com Valores Missing

* **Missing Values** são valores faltantes em colunas, esses podem ser oriundos de falhas em cargas de dados, falhas em crawlers ou até mesmo corrupção de dados.

* Missing Values podem ser um problema em várias situações, como por exemplo, algoritmos de machine learning que não trabalham bem com dados faltantes.

* Estes também podem atrapalhar resultados de análises.

* Vamos aprender como encontrar missing values na base de dados e como manipular esses valores.

In [ ]:
import matplotlib


import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

In [ ]:
dataset.head()

In [ ]:
# Consultando linhas com valores faltantes.
dataset.isnull().sum()

In [ ]:
#Com este comando removemos todas as linhas onde tenha pela menos um registro faltante em algum atributo.
dataset.dropna(inplace=True)

In [ ]:
# É possível ainda, remover somente linhas que estejam com valores faltantes em todas as colunas, veja:
dataset.dropna(how='all', inplace=True)

In [ ]:
#preenche com a media dos valores da coluns floors os values null
dataset['floors'].fillna(dataset['floors'].mean(), inplace=True)

In [ ]:
#preenche com 1 os values null da coluna bedrooms
dataset['bedrooms'].fillna(1, inplace=True)

# Visualização Gráfica - Extraindo Insights

* Vamos agora trabalhar com um tipo de gráfico muito interessante.

* Os gráficos do tipo Boxplot são excelentes ferramentas de análise de dados, principalmente para identificar _**outliers**_.

In [ ]:
import matplotlib

In [ ]:
import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

In [ ]:
# Plota gráfico do tipo Boxplot da coluna bedrooms
# Esse gráfico é muito rico e é possível visualizar Outliers
%matplotlib notebook
matplotlib.style.use('ggplot')

dataset.boxplot(column='bedrooms')

In [ ]:
# Visualizando os estilos de layout disponível
matplotlib.style.available

In [ ]:
# Plota boxplot da coluna 'price' por número de quartos
%matplotlib notebook
dataset.boxplot(column='price', by='bedrooms')

**Correlação **

In [ ]:
# Imprime a correlação de todas as colunas do dataframe (person)
dataset.corr()

In [ ]:
dataset.corr('spearman')

In [ ]:
# Imprime a correlação de spearman (esta leva em consideração a correção positiva e negativa)
dataset.corr('spearman')

In [ ]:
# Imprime a correção de algumas colunas
dataset[['bedrooms','bathrooms','floors','grade','price']].corr()

# Fim

## Valeu!

### #Instagram - Ciencia dos Dados <a href="http://instagram.com/cienciadosdados">instagram.com/cienciadosdados</a>